name: Build and Deploy geesawra.industries

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    env:
      DEBUG_BUILD: ${{ github.ref == 'refs/heads/main' && 'false' || 'true' }}
      HUGO_ALLOW_DRAFTS: ${{ github.ref == 'refs/heads/main' && '' || '-D' }}
      RUST_LOG: atpage_publisher=debug
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'cloudflare-pages' || 'cloudflare-pages-staging' }}
      url: ${{ steps.cf-pages-deploy.outputs.pages-deployment-alias-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Checkout atpage
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: geesawra/atpage
          path: atpage
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f
        with:
          hugo-version: "latest"
          extended: true
      - name: Build website
        run: hugo -d html-output ${{ env.HUGO_ALLOW_DRAFTS }}
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4
        with:
          toolchain: "nightly"
          cache-workspaces: "atpage -> target"
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Nuke existing site
        run: cargo -C atpage -Z unstable-options xtask nuke --pds ${{ vars.PDS_URL }} --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
      - name: Upload new site files
        run: |
          cargo -C atpage -Z unstable-options xtask post \
            --pds ${{ vars.PDS_URL }} \
            --username ${{ secrets.USERNAME }} \
            --password ${{ secrets.PASSWORD }} \
            --src ../html-output \
            --extra-head ../html-output/opengraph.tags
      - name: Copy static files
        run: cp static/_redirects atpage/public && cp static/bsky.svg atpage/public
      - name: Deploy to Cloudflare Pages
        id: cf-pages-deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CF_PAGES_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy atpage/public --project-name=geesawra-industries --commit-dirty=true
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Pushover notification
        if: "!failure()"
        uses: fjogeleit/http-request-action@23ad54bcd1178fcff6a0d17538fa09de3a7f0a4d
        with:
          url: "https://api.pushover.net/1/messages.json"
          method: "POST"
          contentType: "application/x-www-form-urlencoded"
          data: |
            'token=${{ secrets.PUSHOVER_TOKEN}}&user=${{ secrets.PUSHOVER_USER }}&message="Deployed!"&url=${{ steps.cf-pages-deploy.outputs.pages-deployment-alias-url }}'
